title: "Project 1 | YouTube Campaign Analytics"
welcome_line: "Welcome!"
description: |
  This project site is a reimagined real-world business case I faced.
  Featured is a 1:1 practical walk-through of my thinking in the scenario, trade-offs, and execution as I did in my professional settingâ€”shared without the sensitive business details!
author: "Liad Mizrachi"

# MUST match repo name (case-sensitive)
baseurl: "/Data-Backed-Decision-Making-for-Youtube-Campaigns"
url: "https://findliad.github.io"

author_title: "Senior Product Manager"
author_subtitle: "Iâ€™m an independent critical thinker pursuing projects that deepen my technical fluency and showcase product sense in real-world scenarios."
author_photo: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/liad-mizrachi.jpg"

author_links:
  - label: "Portfolio"
    url: "https://findliad.github.io/"
    icon: "ğŸ "
  - label: "Home Git"
    url: "https://github.com/FindLiad"
    icon: "ğŸ“¦"
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/liad-mizrachi/"
    icon: "ğŸ”—"
  - label: "Email Me"
    url: "mailto:Liad%20Mizrachi%20<FindLiad@gmail.com>"
    icon: "âœ‰ï¸"

# Hero screenshot shown in the banner + social preview
hero_screenshot_url: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/finished-dashboard.png"
og_image: "/Data-Backed-Decision-Making-for-Youtube-Campaigns/assets/images/finished-dashboard.png"

# Hero buttons
live_dashboard_url: "https://public.tableau.com/app/profile/liad.mizrachi/viz/YoutubeVisualization_17550201203060/Dashboard1?publish=yes"
next_project_url: "https://findliad.github.io/Human-Resources-Data-Visualization-Dashboard/#site-top"

remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme

readme_index:
  enabled: false
titles_from_headings:
  enabled: false
show_downloads: false



