title: "Data-Backed Decision Making for YouTube Campaigns"
description: "Marketer-facing dashboard to pick high-ROI YouTube channel collabs."
author: "Liad Mizrachi"

author_title: "Senior Product Manager â€¢ AIS Data-Driven Solutions"
author_photo: "/assets/images/author.jpg"

author_links:
  - label: "Portfolio"
    url: "https://findliad.github.io/"
    icon: "ğŸ "
  - label: "Portfolio Repo"
    url: "https://github.com/FindLiad/Data-Backed-Decision-Making-for-Youtube-Campaigns"
    icon: "ğŸ“¦"
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/liadmizrachi/"
    icon: "ğŸ”—"
  - label: "Email"
    url: "mailto:liad@example.com"
    icon: "âœ‰ï¸"

remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme

show_downloads: false
