title: "Data-Backed Decision Making for YouTube Campaigns"
description: "Marketer-facing dashboard to pick high-ROI YouTube channel collabs."
author: "Liad Mizrachi"

author_title: "Senior Product Manager â€¢ AI Data-Driven Solutions"
author_photo: "/assets/images/liad-mizrachi.jpg"

author_links:
  - label: "Portfolio"
    url: "https://findliad.github.io/"
    icon: "ğŸ "
  - label: "Home Repo"
    url: "https://github.com/FindLiad"
    icon: "ğŸ“¦"
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/liad-mizrachi/"
    icon: "ğŸ”—"
  - label: "Email"
    url: "mailto:FindLiad@Gmail.com"
    icon: "âœ‰ï¸"

remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme

show_downloads: false
